using AutoTemplateSelector.Generator;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using Xunit;
using VerifyWpf = AutoTemplateSelector.Generator.Tests.WpfAutoTemplateSelectorSourceGeneratorVerifier<AutoTemplateSelector.Generator.AutoTemplateSelectorSourceGenerator>;

namespace AutoTemplateSelector.Tests;

public class WpfAutoTemplateSelectorSourceGeneratorTests
{
    private const string _crlf = "\r\n";
    private const string _nullableCompleteTemplateSelector = @"namespace Test;

public static partial class SelectorResourceKeys { }

public partial class SelectorResourceDictionary : System.Windows.ResourceDictionary, System.Windows.Markup.IComponentConnector
{
    public void InitializeComponent() {}
    void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {}
}

[AutoTemplateSelector.Generator.AutoTemplateSelector(typeof(SelectorResourceDictionary), ResourceDictionaryKey = typeof(SelectorResourceKeys)) ]
public partial class Selector : System.Windows.Controls.DataTemplateSelector
{
    public System.Windows.DataTemplate Property { get; set; }
}";

    /// <summary>
    /// Verify the generated selector class.
    /// </summary>
    [Fact]
    public async Task Nullable_CompleteCode_Verify_SelectorClass()
    {
        var expectedSelectorSource = @"// <auto-generated/>

namespace Test;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
sealed partial class Selector
{
    public Selector()
    {
        var dictionary = SelectorResourceDictionary.Instance;
        Property = dictionary[SelectorResourceKeys.Property] as System.Windows.DataTemplate;
    }
}
";
        var expectedResourceDictionarySource = @"// <auto-generated/>

namespace Test;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
sealed partial class SelectorResourceDictionary : System.Windows.ResourceDictionary
{
    [System.ThreadStatic]
    private static SelectorResourceDictionary _instance;

    public static SelectorResourceDictionary Instance => _instance ??= new SelectorResourceDictionary();

    public SelectorResourceDictionary()
    {
        InitializeComponent();
    }
}
";

        var expectedResourceKeys = @"// <auto-generated/>

namespace Test;

[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
static partial class SelectorResourceKeys
{
    private static System.Windows.ComponentResourceKey _property;

    public static System.Windows.ResourceKey Property
        => _property ??= new System.Windows.ComponentResourceKey(typeof(SelectorResourceKeys), nameof(Property));

}
";
        var test = new VerifyWpf.Test
        {
            TestState =
            {
                Sources = { _nullableCompleteTemplateSelector },
                GeneratedSources =
                {
                    (typeof(AutoTemplateSelectorSourceGenerator), "Selector.g.cs", SourceText.From(expectedSelectorSource.ReplaceLineEndings(_crlf), Encoding.UTF8)),
                    (typeof(AutoTemplateSelectorSourceGenerator), "Selector.SelectorResourceDictionary.g.cs", SourceText.From(expectedResourceDictionarySource.ReplaceLineEndings(_crlf), Encoding.UTF8)),
                    (typeof(AutoTemplateSelectorSourceGenerator), "Selector.SelectorResourceKeys.g.cs", SourceText.From(expectedResourceKeys.ReplaceLineEndings(_crlf), Encoding.UTF8)),
                },
            }
        };
        test.ExpectedDiagnostics.Add(new DiagnosticResult("GEN001", DiagnosticSeverity.Info)
            .WithSpan(12,22,12,30)
            .WithMessage("Class Selector references ResourceDictionary: Test.SelectorResourceDictionary"));
        await test.RunAsync(TestContext.Current.CancellationToken);
        Assert.True(true);
    }
}
