<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <IsPackable>false</IsPackable>
        <RootNamespace>Bars.Mvvm.FluidGenerator.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ActiproSoftware.Controls.WPF.Bars" />
        <PackageReference Include="ActiproSoftware.Controls.WPF.Bars.Mvvm" />
        <PackageReference Include="ActiproSoftware.Controls.WPF.Shared" />
        <PackageReference Include="Bars.Mvvm.FluentApi.Generator">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="LaDeak.ProtobufSourceGenerator" />
        <PackageReference Include="MahApps.Metro.IconPacks.Material" />
        <PackageReference Include="protobuf-net.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\AutoTemplateSelector.Generator\AutoTemplateSelector.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="true" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Bars.Mvvm\" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Bars.Mvvm\TemplateSelectors\CustomDataTemplateSelectorResourceDictionary.xaml">
        <Generator>MSBuild:Compile</Generator>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="AdditionExtensionMethods.cs" />
    </ItemGroup>

</Project>
