using System.Linq;
using Microsoft.CodeAnalysis;
using Scriban;
using System.Text;

namespace AutoTemplateSelector.Generator;

internal static class AutoTemplateSelectorDictionaryClassGenerator
{
    private static readonly Template ResourceDictionaryInstanceTemplate = Template.Parse(EmbeddedResource.GetContent("Templates/ResourceDictionaryInstance.fg-cs"));

    public static string CreateClass(INamedTypeSymbol dictionaryType)
    {
        StringBuilder sourceBuilder = new();

        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"namespace {dictionaryType.ContainingNamespace.ToDisplayString()};");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sourceBuilder.AppendLine($"sealed partial class {dictionaryType.Name}");
        sourceBuilder.AppendLineStartBracket(0);
        sourceBuilder.Append(ResourceDictionaryInstanceTemplate.Render(new {
            ResourceDictionaryClassName = dictionaryType.Name,
        }, member => member.Name));
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLineWithIndent(1, $"public {dictionaryType.Name}()");
        sourceBuilder.AppendLineStartBracket(1);
        var partsImplementingInterface = dictionaryType.AllInterfaces.Any(i => i.ToDisplayString() == "System.Windows.Markup.IComponentConnector");
        if (partsImplementingInterface)
        {
            sourceBuilder.AppendLineWithIndent(2, "InitializeComponent();");
        }
        else
        {
            sourceBuilder.AppendLineWithIndent(2, "// No parts implementing System.Windows.Markup.IComponentConnector found");
        }

        sourceBuilder.AppendLineEndBracket(1);
        sourceBuilder.AppendLineEndBracket(0);

        return sourceBuilder.ToString();
    }
}
