using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Scriban;
using System.Collections.Immutable;

namespace AutoTemplateSelector.Generator;

/// <summary>
/// This class generates code based on <see cref="AutoTemplateSelectorAttribute"/>
/// to generate ResourceDictionary, ResourceKeys and map these within the ResourceDictionary.
/// </summary>
internal static class AutoTemplateSelectorResourceKeyClassGenerator
{
    private static readonly Template _resourceKeyTemplate = Template.Parse(EmbeddedResource.GetContent("Templates/ComponentResourceKey.fg-cs"));

    public static string GenerateResourceKeys(INamedTypeSymbol classModel)
    {
        var sourceBuilder = new StringBuilder();
        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"namespace {classModel.ContainingNamespace.ToDisplayString()};");
        sourceBuilder.AppendLine();
        var resourceKeyClassName = $"{classModel.Name}ResourceKeys";
        sourceBuilder.AppendLine($"[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sourceBuilder.AppendLine($"static partial class {resourceKeyClassName}");
        sourceBuilder.AppendLineStartBracket(0);
        var properties = PropertyParser.GetRelevantProperties(classModel);
        foreach (var propertyName in properties.Select(p => p.Name).Distinct())
        {
            // Find a way to use Scriban to create the entire class with foreach, though I am not
            // sure if it makes anything easier. Just mentioning here as qn example.
            string variableName = $"_{Char.ToLowerInvariant(propertyName[0])}{propertyName.Substring(1)}";
            var keySetter = _resourceKeyTemplate.Render(new
            {
                VariableName = variableName,
                PropertyName = propertyName,
                ResourceKeyClassName = resourceKeyClassName,
            }, member => member.Name);
            sourceBuilder.AppendLine(keySetter);
        }

        sourceBuilder.AppendLineEndBracket(0);
        return sourceBuilder.ToString();
    }
}