using System.Linq;
using Microsoft.CodeAnalysis;
using System.Text;

namespace AutoTemplateSelector.Generator;

internal static class AutoTemplateSelectorClassGenerator
{
    public static string CreateClass(INamedTypeSymbol classSymbol)
    {
        StringBuilder sourceBuilder = new();

        sourceBuilder.AppendLine("// <auto-generated/>");
        sourceBuilder.AppendLine("#nullable enable");
        sourceBuilder.AppendLine();

        sourceBuilder.AppendLine($"namespace {classSymbol.ContainingNamespace.ToDisplayString()};");
        sourceBuilder.AppendLine();
        sourceBuilder.AppendLine($"[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]");
        sourceBuilder.AppendLine($"sealed partial class {classSymbol.Name}");
        sourceBuilder.AppendLineStartBracket(0);
        sourceBuilder.AppendLineWithIndent(1, $"public {classSymbol.Name}()");
        sourceBuilder.AppendLineStartBracket(1);

        var properties = PropertyParser.GetRelevantProperties(classSymbol);
        sourceBuilder.AppendLineWithIndent(2, $"var dictionary = {classSymbol.Name}ResourceDictionary.Instance;");

        foreach (var property in Enumerable.OfType<IPropertySymbol>(properties))
        {
            sourceBuilder.AppendLineWithIndent(2, NullableContextUtilities.IsAnnotatedNullable(property.Type)
                ? $"{property.Name} = ({property.Type})dictionary[{classSymbol.Name}ResourceKeys.{property.Name}];"
                : $"{property.Name} = dictionary[{classSymbol.Name}ResourceKeys.{property.Name}] as {property.Type};");
        }

        sourceBuilder.AppendLineEndBracket(1);
        sourceBuilder.AppendLineEndBracket(0);

        return sourceBuilder.ToString();
    }
}
