<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <RootNamespace>AutoTemplateSelector.Generator</RootNamespace>
    </PropertyGroup>
    
    <PropertyGroup>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <PackageId>AutoTemplateSelector.Generator</PackageId>
        <Authors>Bjørnar Sundsbø</Authors>
        <Copyright>Bjørnar Sundsbø</Copyright>
        <!-- TODO: Update the project URL -->
        <PackageProjectUrl>https://github.com/bsundsbo/Bars.Mvvm</PackageProjectUrl>
        <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Description>Automate ResourceKeys and DataTemplate property mapping to reduce boilerplate code.</Description>
        <PackageTags>WPF, Windows, UI, XAML, MVVM, ViewModel, View, Library, .NET, Source Generator, DataTemplateSelector, ItemTemplateSelector</PackageTags>
        <!-- Project is packable -->
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Package the generator in the analyzer directory of the nuget package -->
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
        <None Include="README.md" Pack="true" PackagePath="/" />
        <None Include="AnalyzerReleases.Shipped.md" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="BarTemplateSelectorCodeGenerator\Templates\ComponentResourceKey.fg-cs" />
      <EmbeddedResource Include="BarTemplateSelectorCodeGenerator\Templates\ResourceDictionaryInstance.fg-cs" />
    </ItemGroup>

    <PropertyGroup>
        <PackageScribanIncludeSource>true</PackageScribanIncludeSource>
        <DefineConstants>SCRIBAN_NO_ASYNC</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Scriban" IncludeAssets="Build" PrivateAssets="all" />
    </ItemGroup>

</Project>
